# tests/test_compliance_styling.py
"""T1.7+T1.8 styling 合规闸门 + 合规报告生成。

覆盖三块：
1. 回归门禁：默认构造 OCRToASSOptimizer（无 font_compliance）时
   ``_get_ass_header()`` 输出与改动前逐字节一致（黄金字符串硬拷贝自
   当前实现，含 NoteBox 分支带/不带场景策略两种），且不生成任何
   ``*_compliance_report.*`` 文件。
2. font_intel.integration 单元：``apply_compliance_to_header`` 的
   allow 保留 / prompt 非交互降级保留并记录 / replace_auto 置信度门槛
   替换 / 模板模式只收集不改字节 / 按去重字体名出决策；
   ``write_compliance_report`` 的 md/json 命名、免责声明原句、字段齐全、
   无决策零文件。
3. 生成器接线端到端：启用合规后 KO 行自动替换、其余 Style 行与 Format
   行不动、报告与 ASS 同目录；db 缺失优雅降级全 unknown；关闭合规零
   新文件；模板模式输出与不合规运行逐字节一致；决策跨多次头部生成
   去重累积、报告只写一次。
"""

from __future__ import annotations

import json
import os
import sys


PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

from core.subtitle_generator.generator import OCRToASSOptimizer  # noqa: E402
from font_intel.fonts_db import FontsDB  # noqa: E402


# ── 黄金字符串：改动前默认头部逐字节硬拷贝（1280x720，视频名 in.mp4）──

GOLDEN_DEFAULT_HEADER = """[Script Info]
Title: in - Generated by Subtitle-OCR
ScriptType: v4.00+
WrapStyle: 0
PlayResX: 1280
PlayResY: 720
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,思源黑体 CN,43,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,1,2,10,10,10,1
Style: CH,思源黑体 CN,43,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,1,2,10,10,10,1
Style: JP,源ノ角ゴシック JP,43,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,1,2,10,10,10,1
Style: KO,Malgun Gothic,43,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,1,2,10,10,10,1
Style: RU,Arial,43,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,1,2,10,10,10,1
Style: Top,思源黑体 CN,36,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,1,8,10,10,10,1
Style: Scene,思源黑体 CN,29,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1,0,5,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""

GOLDEN_NOTEBOX_HEADER = """[Script Info]
Title: in - Generated by Subtitle-OCR
ScriptType: v4.00+
WrapStyle: 0
PlayResX: 1280
PlayResY: 720
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,思源黑体 CN,43,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,1,2,10,10,10,1
Style: CH,思源黑体 CN,43,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,1,2,10,10,10,1
Style: JP,源ノ角ゴシック JP,43,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,1,2,10,10,10,1
Style: KO,Malgun Gothic,43,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,1,2,10,10,10,1
Style: RU,Arial,43,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,1,2,10,10,10,1
Style: Top,思源黑体 CN,36,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,1,8,10,10,10,1
Style: Scene,思源黑体 CN,29,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1,0,5,10,10,10,1
Style: NoteBox,思源黑体 CN,29,&H00FFFFFF,&H000000FF,&H00000000,&H80000000&,0,0,0,0,100,100,0,0,3,1,0,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""

DISCLAIMER = "本报告不构成法律意见，商用前请自行核实授权条款"


# ── 构造辅助 ─────────────────────────────────────────────────────

def _make_optimizer(tmp_path, **kw) -> OCRToASSOptimizer:
    return OCRToASSOptimizer(
        video_path=str(tmp_path / "in.mp4"),
        output_path=str(tmp_path / "out.ass"),
        fps=25.0,
        width=1280,
        height=720,
        **kw,
    )


def _make_item(frame_num, text, box):
    poly = [[box[0], box[1]], [box[2], box[1]], [box[2], box[3]], [box[0], box[3]]]
    data = {
        "dt_polys": [poly],
        "rec_polys": [poly],
        "rec_texts": [text],
        "rec_scores": [0.95],
        "rec_boxes": [list(box)],
    }
    return (data, frame_num, "roi_0", frame_num / 25.0)


def _items():
    # 底部区域 → BOTTOM 组，产出对白事件（头部样式行与事件无关）。
    return [_make_item(f, "学成归来", (100, 600, 500, 650)) for f in range(10, 21)]


def _seed_db_file(path) -> str:
    """种子库：思源黑体 CN=open_source，Malgun Gothic=commercial_paid。"""
    db = FontsDB(str(path))
    db.import_seed([
        {"table": "fonts", "canonical_name": "思源黑体 CN",
         "license_category": "open_source",
         "official_url": "https://github.com/adobe-fonts/source-han-sans",
         "source": "test-seed"},
        {"table": "fonts", "canonical_name": "Malgun Gothic",
         "license_category": "commercial_paid",
         "official_url": "https://www.fonts.go.kr/malgun",
         "source": "test-seed"},
    ])
    db.close()
    return str(path)


def _no_report_files(tmp_path):
    return sorted(p.name for p in tmp_path.glob("*_compliance_report.*"))


def _replace_auto_config(db_path: str, confidence=0.9):
    from font_intel.compliance import ComplianceRules
    from font_intel.integration import FontComplianceConfig

    rules = ComplianceRules()
    rules.set_override("commercial_paid", "personal", "replace_auto")
    return FontComplianceConfig(
        enabled=True,
        scene="personal",
        rules=rules,
        db_path=db_path,
        confidence=confidence,
        alternatives_provider=lambda name: ["思源黑体 CN"],
    )


# ── 1. 回归门禁（改动前后都必须通过）────────────────────────────

class TestDefaultHeaderRegressionGate:

    def test_default_header_golden_plain(self, tmp_path):
        conv = _make_optimizer(tmp_path)
        assert conv._get_ass_header() == GOLDEN_DEFAULT_HEADER
        assert _no_report_files(tmp_path) == []

    def test_default_header_golden_with_notebox(self, tmp_path):
        conv = _make_optimizer(
            tmp_path, roi_scene_text_policies={"roi_0": "external"})
        assert conv._get_ass_header() == GOLDEN_NOTEBOX_HEADER
        assert _no_report_files(tmp_path) == []


# ── 2. apply_compliance_to_header 单元 ──────────────────────────

class TestApplyComplianceToHeader:

    def test_allow_keeps_open_source_font(self, tmp_path):
        from font_intel.integration import FontComplianceConfig, apply_compliance_to_header
        db_path = _seed_db_file(tmp_path / "fonts.db")
        cfg = FontComplianceConfig(enabled=True, db_path=db_path)
        new_header, decisions = apply_compliance_to_header(
            GOLDEN_DEFAULT_HEADER, cfg)
        # 开源字体放行：原名保留，头部仅有的思源黑体 Style 行不动。
        assert "Style: Default,思源黑体 CN,43," in new_header
        by_font = {d["font_name"]: d for d in decisions}
        assert by_font["思源黑体 CN"]["action"] == "allow"
        assert by_font["思源黑体 CN"]["license_category"] == "open_source"
        assert by_font["思源黑体 CN"]["final_font"] == "思源黑体 CN"
        assert by_font["思源黑体 CN"]["granted"] is False

    def test_prompt_non_interactive_keeps_and_records(self, tmp_path):
        from font_intel.integration import FontComplianceConfig, apply_compliance_to_header
        db_path = _seed_db_file(tmp_path / "fonts.db")
        cfg = FontComplianceConfig(
            enabled=True, db_path=db_path)  # interactive 缺省 False
        new_header, decisions = apply_compliance_to_header(
            GOLDEN_DEFAULT_HEADER, cfg)
        # 商用需授权：非交互模式降级为保留原名 + 记录决策，绝不阻塞出片。
        assert "Style: KO,Malgun Gothic,43," in new_header
        by_font = {d["font_name"]: d for d in decisions}
        d = by_font["Malgun Gothic"]
        assert d["action"] == "prompt"
        assert d["license_category"] == "commercial_paid"
        assert d["final_font"] == "Malgun Gothic"
        assert "非交互" in d["reason"]
        assert d["official_url"] == "https://www.fonts.go.kr/malgun"
        assert d["styles"] == ["KO"]

    def test_replace_auto_replaces_only_target_style(self, tmp_path):
        from font_intel.integration import apply_compliance_to_header
        db_path = _seed_db_file(tmp_path / "fonts.db")
        cfg = _replace_auto_config(db_path, confidence=0.9)
        new_header, decisions = apply_compliance_to_header(
            GOLDEN_DEFAULT_HEADER, cfg)
        # KO 行字体被替换为替代字体链第一项。
        assert "Style: KO,思源黑体 CN,43," in new_header
        assert "Style: KO,Malgun Gothic" not in new_header
        # 其余 Style 行与 Format 行逐字节不动。
        assert "Style: JP,源ノ角ゴシック JP,43," in new_header
        assert "Style: RU,Arial,43," in new_header
        assert "Style: Default,思源黑体 CN,43," in new_header
        assert ("Format: Name, Fontname, Fontsize, PrimaryColour,"
                " SecondaryColour") in new_header
        by_font = {d["font_name"]: d for d in decisions}
        d = by_font["Malgun Gothic"]
        assert d["action"] == "replace_auto"
        assert d["final_font"] == "思源黑体 CN"
        assert d["replaced"] is True
        assert d["styles"] == ["KO"]

    def test_replace_auto_low_confidence_degrades_to_keep(self, tmp_path):
        from font_intel.integration import apply_compliance_to_header
        db_path = _seed_db_file(tmp_path / "fonts.db")
        cfg = _replace_auto_config(db_path, confidence=0.6)
        new_header, decisions = apply_compliance_to_header(
            GOLDEN_DEFAULT_HEADER, cfg)
        # 置信度不达门槛 → decide 内部降级 prompt → 保留原名。
        assert "Style: KO,Malgun Gothic,43," in new_header
        by_font = {d["font_name"]: d for d in decisions}
        d = by_font["Malgun Gothic"]
        assert d["action"] == "prompt"
        assert d["final_font"] == "Malgun Gothic"
        assert d["replaced"] is False

    def test_template_mode_collects_without_modifying(self, tmp_path):
        from font_intel.integration import FontComplianceConfig, apply_compliance_to_header
        db_path = _seed_db_file(tmp_path / "fonts.db")
        cfg = FontComplianceConfig(enabled=True, db_path=db_path)
        new_header, decisions = apply_compliance_to_header(
            GOLDEN_DEFAULT_HEADER, cfg, template_mode=True)
        # 用户模板不重写：逐字节原样返回，仅收集决策。
        assert new_header == GOLDEN_DEFAULT_HEADER
        assert {d["font_name"] for d in decisions} >= {"Malgun Gothic",
                                                       "思源黑体 CN"}

    def test_decisions_deduped_by_font_name(self, tmp_path):
        from font_intel.integration import FontComplianceConfig, apply_compliance_to_header
        db_path = _seed_db_file(tmp_path / "fonts.db")
        cfg = FontComplianceConfig(enabled=True, db_path=db_path)
        _header, decisions = apply_compliance_to_header(
            GOLDEN_DEFAULT_HEADER, cfg)
        # 去重：思源黑体 CN 占 4 条 Style 行只出 1 条决策，多个 style 名
        # 记录在其下；总决策数 = 去重字体数（4）。
        assert len(decisions) == 4
        by_font = {d["font_name"]: d for d in decisions}
        assert by_font["思源黑体 CN"]["styles"] == ["Default", "CH", "Top",
                                                    "Scene"]
        assert by_font["思源黑体 CN"]["style"] == "Default"

    def test_none_or_disabled_config_is_noop(self):
        from font_intel.integration import FontComplianceConfig, apply_compliance_to_header
        header, decisions = apply_compliance_to_header(
            GOLDEN_DEFAULT_HEADER, None)
        assert header == GOLDEN_DEFAULT_HEADER
        assert decisions == []
        cfg = FontComplianceConfig(enabled=False)
        header, decisions = apply_compliance_to_header(
            GOLDEN_DEFAULT_HEADER, cfg)
        assert header == GOLDEN_DEFAULT_HEADER
        assert decisions == []


# ── 3. write_compliance_report 单元 ─────────────────────────────

class TestWriteComplianceReport:

    def _decisions(self, tmp_path):
        from font_intel.integration import FontComplianceConfig, apply_compliance_to_header
        db_path = _seed_db_file(tmp_path / "fonts.db")
        cfg = FontComplianceConfig(enabled=True, db_path=db_path)
        _header, decisions = apply_compliance_to_header(
            GOLDEN_DEFAULT_HEADER, cfg)
        assert decisions
        return decisions

    def test_report_files_naming_and_content(self, tmp_path):
        from font_intel.integration import write_compliance_report
        decisions = self._decisions(tmp_path)
        ass_path = tmp_path / "movie.ass"
        md_path, json_path = write_compliance_report(
            decisions, ass_path, meta={"video": "movie.mp4"})
        # 与 ASS 同目录、命名 <stem>_compliance_report.md/.json。
        assert md_path == tmp_path / "movie_compliance_report.md"
        assert json_path == tmp_path / "movie_compliance_report.json"
        assert md_path.exists() and json_path.exists()

        md_text = md_path.read_text(encoding="utf-8")
        assert DISCLAIMER in md_text  # 免责声明原句
        assert "Malgun Gothic" in md_text
        assert "思源黑体 CN" in md_text
        assert "commercial_paid" in md_text
        assert "prompt" in md_text
        assert "https://www.fonts.go.kr/malgun" in md_text  # 经消毒的官方链接

        payload = json.loads(json_path.read_text(encoding="utf-8"))
        assert payload["disclaimer"] == DISCLAIMER
        assert payload["meta"] == {"video": "movie.mp4"}
        assert payload["ass_path"] == str(ass_path)
        assert payload["decisions"]
        for entry in payload["decisions"]:
            for key in ("style", "styles", "font_name", "final_font",
                        "action", "license_category", "reason",
                        "official_url"):
                assert key in entry

    def test_empty_decisions_writes_no_files(self, tmp_path):
        from font_intel.integration import write_compliance_report
        result = write_compliance_report([], tmp_path / "x.ass")
        assert result == (None, None)
        assert list(tmp_path.glob("*")) == []


# ── 4. 生成器接线端到端 ─────────────────────────────────────────

class TestGeneratorComplianceIntegration:

    def test_replace_auto_end_to_end_with_report(self, tmp_path):
        db_path = _seed_db_file(tmp_path / "fonts.db")
        conv = _make_optimizer(
            tmp_path, font_compliance=_replace_auto_config(db_path, 0.9))
        conv.convert_from_memory(iter(_items()))

        text = (tmp_path / "out.ass").read_text(encoding="utf-8-sig")
        assert "Style: KO,思源黑体 CN,43," in text
        assert "Style: KO,Malgun Gothic" not in text
        # 其余 Style 行不动。
        assert "Style: JP,源ノ角ゴシック JP,43," in text
        assert "Style: Default,思源黑体 CN,43," in text

        md_path = tmp_path / "out_compliance_report.md"
        json_path = tmp_path / "out_compliance_report.json"
        assert md_path.exists() and json_path.exists()
        md_text = md_path.read_text(encoding="utf-8")
        assert DISCLAIMER in md_text
        assert "Malgun Gothic" in md_text  # 被替换的字体也入报告
        payload = json.loads(json_path.read_text(encoding="utf-8"))
        by_font = {d["font_name"]: d for d in payload["decisions"]}
        assert by_font["Malgun Gothic"]["action"] == "replace_auto"
        assert by_font["Malgun Gothic"]["final_font"] == "思源黑体 CN"

    def test_enabled_missing_db_degrades_to_unknown(self, tmp_path):
        from font_intel.integration import FontComplianceConfig
        missing = tmp_path / "no_such_fonts.db"
        conv = _make_optimizer(
            tmp_path, font_compliance=FontComplianceConfig(
                enabled=True, db_path=str(missing)))
        # 不抛异常：库缺失按 unknown 从严（prompt 保留原名），ASS 正常生成。
        conv.convert_from_memory(iter(_items()))
        text = (tmp_path / "out.ass").read_text(encoding="utf-8-sig")
        assert "Style: KO,Malgun Gothic,43," in text
        assert "Style: JP,源ノ角ゴシック JP,43," in text
        payload = json.loads(
            (tmp_path / "out_compliance_report.json").read_text(
                encoding="utf-8"))
        assert payload["decisions"]
        assert all(d["license_category"] == "unknown"
                   for d in payload["decisions"])

    def test_disabled_config_zero_new_files(self, tmp_path):
        from font_intel.integration import FontComplianceConfig
        baseline_dir = tmp_path / "baseline"
        baseline_dir.mkdir()
        base = OCRToASSOptimizer(
            video_path=str(baseline_dir / "in.mp4"),
            output_path=str(baseline_dir / "out.ass"),
            fps=25.0, width=1280, height=720)
        base.convert_from_memory(iter(_items()))

        conv = _make_optimizer(
            tmp_path, font_compliance=FontComplianceConfig(
                enabled=False, db_path=str(tmp_path / "fonts.db")))
        conv.convert_from_memory(iter(_items()))

        # 关闭合规：输出与默认构造逐字节一致，且零合规报告新文件。
        assert (tmp_path / "out.ass").read_bytes() == \
            (baseline_dir / "out.ass").read_bytes()
        assert _no_report_files(tmp_path) == []
        assert _no_report_files(baseline_dir) == []

    def test_template_mode_end_to_end_bytes_identical(self, tmp_path):
        from font_intel.integration import FontComplianceConfig
        template = tmp_path / "template.ass"
        template.write_text(
            "[Script Info]\nTitle: Custom\nPlayResX: 1920\nPlayResY: 1080\n"
            "ScaledBorderAndShadow: yes\n\n[V4+ Styles]\n"
            "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour,"
            " OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut,"
            " ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow,"
            " Alignment, MarginL, MarginR, MarginV, Encoding\n"
            "Style: Default,Malgun Gothic,48,&H00FFFFFF,&H000000FF,"
            "&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,1,2,10,10,10,1\n"
            "Style: Sign,思源黑体 CN,60,&H00FFFFFF,&H000000FF,&H00000000,"
            "&H00000000,0,0,0,0,100,100,0,0,1,2,1,2,10,10,10,1\n\n"
            "[Events]\n"
            "Format: Layer, Start, End, Style, Name, MarginL, MarginR,"
            " MarginV, Effect, Text\n",
            encoding="utf-8")
        template_bytes = template.read_bytes()

        baseline_dir = tmp_path / "baseline"
        baseline_dir.mkdir()
        base = OCRToASSOptimizer(
            video_path=str(baseline_dir / "in.mp4"),
            output_path=str(baseline_dir / "out.ass"),
            fps=25.0, width=1280, height=720,
            template_path=str(template))
        base.convert_from_memory(iter(_items()))

        db_path = _seed_db_file(tmp_path / "fonts.db")
        conv = _make_optimizer(
            tmp_path,
            template_path=str(template),
            font_compliance=FontComplianceConfig(
                enabled=True, db_path=db_path))
        conv.convert_from_memory(iter(_items()))

        # 模板分支只收集不重写：输出与不合规运行逐字节一致（含 PlayRes
        # 替换等既有逻辑），商业字体名原样保留；模板文件本身未被改动。
        assert (tmp_path / "out.ass").read_bytes() == \
            (baseline_dir / "out.ass").read_bytes()
        text = (tmp_path / "out.ass").read_text(encoding="utf-8-sig")
        assert "Style: Default,Malgun Gothic,48," in text
        assert template.read_bytes() == template_bytes

        # 决策已收集，报告列出该商业字体。
        md_text = (tmp_path / "out_compliance_report.md").read_text(
            encoding="utf-8")
        assert "Malgun Gothic" in md_text
        assert DISCLAIMER in md_text
        # 基线（未启用合规）零报告文件。
        assert _no_report_files(baseline_dir) == []

    def test_decisions_dedup_and_report_written_once(self, tmp_path):
        db_path = _seed_db_file(tmp_path / "fonts.db")
        conv = _make_optimizer(
            tmp_path, font_compliance=_replace_auto_config(db_path, 0.9))
        # 头部生成两次：决策仍按去重字体名各一条（不随调用翻倍）。
        conv._get_ass_header()
        conv._get_ass_header()
        assert len(conv._compliance_decisions) == 4
        conv.convert_from_memory(iter(_items()))
        json_path = tmp_path / "out_compliance_report.json"
        assert json_path.exists()
        first = json_path.read_bytes()
        # 收尾重复调用：报告只写一次（幂等），内容不被重建。
        conv._write_compliance_report_if_needed()
        conv._write_compliance_report_if_needed()
        assert json_path.read_bytes() == first
